### ISSUE TITLE
error C2719: 'lh': formal parameter with __declspec(align('16')) won't be aligned

### ISSUE THREAD

**Issue by Starl1ght** [g-truc/glm#325]
Hi guys, stumbled upon this issue.

Can be fixed by #define GLM_FORCE_PURE but well... this is not good

Visual Studio 2013 + Win7x64.
Code is simple #include <glm/ext.hpp> without anything

**Comment by Starl1ght** [comment]
used latest version 0.9.6.3, this needs to be fixed without workarounds and stuff

**Comment by elInfidel** [comment]
I've been getting this issue constantly anywhere I'm using glm.
Windows 8.1x64 with vs2013 and glm 0.9.6.3

**Comment by laelath** [comment]
This has already been mentioned  before [here](https://github.com/g-truc/glm/issues/316)
The workaround I use is to comment out #define GLM_HAS_ANONYMOUS_UNION (GLM_LANG & GLM_LANG_CXXMS_FLAG) at line 675 in glm/detail/setup.hpp
I have no idea why this is causing this issue, and i think the person who responded in the other one knows much more about it than me.

**Comment by skln131313** [comment]
A simple work around to the problem, passing by reference and then creating the copy in the code instead.

glm/gtx/scalar_multiplication.hpp

```C++
#define GLM_IMPLEMENT_SCAL_MULT(Vec) \
	template <typename T> \
	return_type_scalar_multiplication<T, Vec> \
	operator*(T const & s, Vec const & rh){ \
		return Vec(rh) *= static_cast<float>(s); \
	} \
	 \
	template <typename T> \
	return_type_scalar_multiplication<T, Vec> \
	operator*(Vec const & lh, T const & s){ \
		return Vec(lh) *= static_cast<float>(s); \
	} \
	 \
	template <typename T> \
	return_type_scalar_multiplication<T, Vec> \
	operator/(Vec const & lh, T const & s){ \
		return Vec(lh) *= 1.0f / s; \
	}
```

**Comment by Gibgezr** [comment]
Tried skln131313's workaround, didn't fix the warnings for me.

**Comment by skln131313** [comment]
It's not a warning, it's an error. You are probably having some other issue.

**Comment by Gibgezr** [comment]
Well, my problem is fixed by following laelath's advice and commenting out a line. Seems that VS2013 doesn't like the anonymous union. Any other compilers throwing up an issue with this?

**Comment by Groovounet** [comment]
Hi,

Can you still reproduce this issue on the master branch?
I never managed to reproduce it. A repro case would be great!

Thanks,
Christophe

**Comment by skln131313** [comment]
Yes it still happens to me using the master branch.

It needs to be built for x86, the error doesn't happen with x64. Using Visual Studio 2013 and 2015.

**Comment by Bastl34** [comment]
Hi

The bug is still present in the master branch.

Sample to reproduce it:
(Visual Studio 2013 Community, 32Bit, Debug Mode)
```cpp

#include <glm.hpp>

glm::vec4 test(const glm::vec4 test)
{
	return test;
}

void main()
{
	auto t = test(glm::vec4());
}
```

(The same sample with `vec3` is working)


This is the error:
```cpp
main.cpp(4): error C2719: 'test': formal parameter with __declspec(align('16')) won't be aligned
```
