### ISSUE TITLE
Compile errors occurred when using functions in glm/gtc/reciprocal.hpp

### ISSUE THREAD

**Issue by redcap97** [g-truc/glm#348]
Branch: master
Compilers: g++ 5.1.0, clang++ 3.6.1

**sample.cpp**

```cpp
#include <glm/gtc/reciprocal.hpp>

int main(int argc, char *argv[]) {
  glm::sec(0.0f);
  glm::csc(0.0f);
  glm::cot(0.0f);
  glm::asec(0.0f);
  glm::acsc(0.0f);
  glm::acot(0.0f);
  glm::sech(0.0f);
  glm::csch(0.0f);
  glm::coth(0.0f);
  glm::asech(0.0f);
  glm::acsch(0.0f);
  glm::acoth(0.0f);
  return 0;
}
```

clang++

```
arch:/tmp/glm$ clang++ -Iglm sample.cpp
sample.cpp:4:3: error: call to 'sec' is ambiguous
  glm::sec(0.0f);
  ^~~~~~~~
glm/glm/gtc/reciprocal.hpp:61:24: note: candidate function [with genType = float]
        GLM_FUNC_DECL genType sec(genType const & angle);
                              ^
glm/glm/gtc/reciprocal.inl:40:29: note: candidate function [with genType = float]
        GLM_FUNC_QUALIFIER genType sec(genType angle)
                                   ^
sample.cpp:5:2: error: call to 'csc' is ambiguous
        glm::csc(0.0f);
        ^~~~~~~~
glm/glm/gtc/reciprocal.hpp:68:24: note: candidate function [with genType = float]
        GLM_FUNC_DECL genType csc(genType const & angle);
                              ^
glm/glm/gtc/reciprocal.inl:55:29: note: candidate function [with genType = float]
        GLM_FUNC_QUALIFIER genType csc(genType angle)
                                   ^
sample.cpp:6:2: error: call to 'cot' is ambiguous
        glm::cot(0.0f);
        ^~~~~~~~
glm/glm/gtc/reciprocal.hpp:75:24: note: candidate function [with genType = float]
        GLM_FUNC_DECL genType cot(genType const & angle);
                              ^
glm/glm/gtc/reciprocal.inl:70:29: note: candidate function [with genType = float]
        GLM_FUNC_QUALIFIER genType cot(genType angle)
                                   ^
sample.cpp:7:2: error: call to 'asec' is ambiguous
        glm::asec(0.0f);
        ^~~~~~~~~
glm/glm/gtc/reciprocal.hpp:81:24: note: candidate function [with genType = float]
        GLM_FUNC_DECL genType asec(genType const & x);
                              ^
glm/glm/gtc/reciprocal.inl:87:29: note: candidate function [with genType = float]
        GLM_FUNC_QUALIFIER genType asec(genType x)
                                   ^
sample.cpp:8:2: error: call to 'acsc' is ambiguous
        glm::acsc(0.0f);
        ^~~~~~~~~

...
```

g++

```
arch:/tmp/glm$ g++ -Iglm sample.cpp
sample.cpp: In function ‘int main(int, char**)’:
sample.cpp:4:16: error: call of overloaded ‘sec(float)’ is ambiguous
   glm::sec(0.0f);
                ^
In file included from sample.cpp:1:0:
glm/glm/gtc/reciprocal.hpp:61:24: note: candidate: genType glm::sec(const genType&) [with genType = float]
  GLM_FUNC_DECL genType sec(genType const & angle);
                        ^
In file included from glm/glm/gtc/reciprocal.hpp:134:0,
                 from sample.cpp:1:
glm/glm/gtc/reciprocal.inl:40:29: note: candidate: genType glm::sec(genType) [with genType = float]
  GLM_FUNC_QUALIFIER genType sec(genType angle)
                             ^
sample.cpp:5:15: error: call of overloaded ‘csc(float)’ is ambiguous
  glm::csc(0.0f);
               ^
In file included from sample.cpp:1:0:
glm/glm/gtc/reciprocal.hpp:68:24: note: candidate: genType glm::csc(const genType&) [with genType = float]
  GLM_FUNC_DECL genType csc(genType const & angle);
                        ^
In file included from glm/glm/gtc/reciprocal.hpp:134:0,
                 from sample.cpp:1:
glm/glm/gtc/reciprocal.inl:55:29: note: candidate: genType glm::csc(genType) [with genType = float]
  GLM_FUNC_QUALIFIER genType csc(genType angle)
                             ^
sample.cpp:6:15: error: call of overloaded ‘cot(float)’ is ambiguous
  glm::cot(0.0f);
               ^
In file included from sample.cpp:1:0:
glm/glm/gtc/reciprocal.hpp:75:24: note: candidate: genType glm::cot(const genType&) [with genType = float]
  GLM_FUNC_DECL genType cot(genType const & angle);
                        ^
In file included from glm/glm/gtc/reciprocal.hpp:134:0,
                 from sample.cpp:1:
glm/glm/gtc/reciprocal.inl:70:29: note: candidate: genType glm::cot(genType) [with genType = float]
  GLM_FUNC_QUALIFIER genType cot(genType angle)
                             ^
sample.cpp:7:16: error: call of overloaded ‘asec(float)’ is ambiguous
  glm::asec(0.0f);
                ^
In file included from sample.cpp:1:0:
glm/glm/gtc/reciprocal.hpp:81:24: note: candidate: genType glm::asec(const genType&) [with genType = float]
  GLM_FUNC_DECL genType asec(genType const & x);
                        ^
In file included from glm/glm/gtc/reciprocal.hpp:134:0,
                 from sample.cpp:1:
glm/glm/gtc/reciprocal.inl:87:29: note: candidate: genType glm::asec(genType) [with genType = float]
  GLM_FUNC_QUALIFIER genType asec(genType x)
                             ^
sample.cpp:8:16: error: call of overloaded ‘acsc(float)’ is ambiguous
  glm::acsc(0.0f);
                ^

...
```

**Comment by Groovounet** [comment]
This issue has been fixed in GLM 0.9.6 branch for 0.9.6.4 release.

Thanks for contributing!
Christophe

**Comment by clarejor** [comment]
I'm still getting this issue in the 0.9.7.1 branch. Looks like glm/gtc/reciprocal.inl isn't showing the const changes from commit cd78ac6.

**Comment by kankaristo** [comment]
@Groovounet, this still seems to be broken in 0.9.7.3, but fixed in the Git version?
