### ISSUE TITLE
Some tests fail when compiled with GCC 7.1.0

### ISSUE THREAD

**Issue by gsliepen** [g-truc/glm#666]
When compiling using GCC 7.1.0, some tests fail:

> The following tests FAILED:
>         12 - test-core_type_mat2x4 (Failed)
>         15 - test-core_type_mat3x4 (Failed)
>         18 - test-core_type_mat4x4 (Failed)

In case of the mat2x4 test, it's the following line that's failing:

    entry<glm::mat3x4>();

As soon as I try to add some debug statements, the problem disappears. I'm unsure if this is a bug in GCC or if GLM is depending on some undefined behaviour here.

**Comment by Groovounet** [comment]
This issue is fixed in master branch.

Thanks for reporting,
Christophe

**Comment by muep** [comment]
I am still getting this problem in Fedora 26 with master branch of GLM.

**Comment by gsliepen** [comment]
On Tue, Aug 15, 2017 at 06:32:51PM +0000, Joonas Sarajärvi wrote:

> I am still getting this problem in Fedora 26 with master branch of GLM.

I also still see the same problem with revision
e76fca75a0e7808ae767dca58c6d1f97a17c3048 on Debian unstable, GCC
7.1.0-13, on a Haswell processor.

Note that this never was a build error; the test compiled fine but
failed when running it.

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>

**Comment by Groovounet** [comment]
Hi,
This issue is now fixed on master branch. I didn't repro with GCC 6.1.0 for me but I could repro on Windows with GCC 7.1.0.
Thanks for reporting,
Christophe

**Comment by gsliepen** [comment]
On Wed, Aug 16, 2017 at 10:10:19PM +0000, Christophe wrote:

> This issue is now fixed on master branch. I didn't repro with GCC 6.1.0 for me but I could repro on Windows with GCC 7.1.0.

Thanks, the problem is indeed gone!

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>

**Comment by justinkb** [comment]
Based on the logic of the fixes, is it right for me to conclude that bad test code was being produced, and not (necessarily) bad actual glm code? So, if I'm using code that failed the test, I can't conclude anything about the functionality of the code (if the test was faulty, whatever functionality it was supposed to be testing wasn't actually being tested). If I apply the test patch locally, and compile everything (using the exact same build environment) and the tests pass that time, I should be reasonably be able to conclude that the code I was running previously was in fact functionally correct, right?
